---
title: "ADPP/ADPP-like comparison report"
output: html_document
params:
  unique_keys: NULL
  comparison_result: NULL
  row_count_result: NULL
  column_count_result: NULL
  rounding_result: NULL
  value_result: NULL
  comments: NULL
  date_time: NULL
  datasets: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(htmltools)
library(knitr)

```



## Comparison Run Information

```{r unique_keys}
      report_metadata_ui(
        comparison_date = params$date_time$date,
        comparison_time = params$date_time$time,
        dataset1_name = params$datasets$dataset1_name,
        dataset2_name = params$datasets$dataset2_name,
        selected_keys = params$unique_keys
      )
```

---

<!-- New structure Check Section -->

## Structure and Content Checks

```{r comparison_result}
params$comparison_result$results_structure_ui

if (nzchar(params$comments$structure_and_content)) {
  comment_text <- paste0("### Structure and Content Checks Comment\n", params$comments$structure_and_content)
  knitr::asis_output(comment_text)
}
```

---

# OLD

<!-- ## Number of Rows Check -->

<!-- ```{r row_count_check comments} -->
<!-- row_count_check_markdown(params$row_count_result, params$unique_keys) -->

<!-- if (nzchar(params$comments$row_count)) { -->
<!--   comment_text <- paste0("##### Comment\n\n", params$comments$row_count) -->
<!--   knitr::asis_output(comment_text) -->
<!-- } -->
<!-- ``` -->


<!-- ## Number of Columns comparison -->

<!-- ```{r column_count_check} -->
<!-- column_count_check_markdown(params$column_count_result) -->

<!-- if (nzchar(params$comments$column_count)) { -->
<!--   comment_text <- paste0("##### Comment\n\n", params$comments$column_count) -->
<!--   knitr::asis_output(comment_text) -->
<!-- } -->
<!-- ``` -->


## Decimal Place Check

```{r rounding_check}
rounding_check_markdown(params$rounding_result)

if (nzchar(params$comments$rounding)) {
  comment_text <- paste0("##### Comment\n\n", params$comments$rounding)
  knitr::asis_output(comment_text)
}
```


## Value Check

```{r value_check}
value_check_markdown(params$value_result, params$unique_keys)

if (nzchar(params$comments$value)) {
  comment_text <- paste0("##### Comment\n\n", params$comments$value)
  knitr::asis_output(comment_text)
}
```

